# Generated by Django 2.2.16 on 2020-11-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dname',
        ),
    ]
