# Generated by Django 2.2.16 on 2020-11-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20201105_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
